//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cursos0._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Curso()
        {
            this.Lecciones = new HashSet<Leccion>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Nivel { get; set; }
        public string TpCurso { get; set; }
        public string ImagCrs { get; set; }
        public string VideoIntr { get; set; }
        public string Descripcion { get; set; }
        public int InstructorId { get; set; }
    
        public virtual Instructor Instructor { get; set; }
        public virtual DetCrs_Est DetCrs_Est { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Leccion> Lecciones { get; set; }
    }
}
