//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cursos0._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estudiante
    {
        public int Id { get; set; }
        public string Idio_Cult { get; set; }
        public string Nivel { get; set; }
        public string ImagEst { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual DetCrs_Est DetCrs_Est { get; set; }
        public virtual ResultadoEva ResultadoEva { get; set; }
    }
}
