//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cursos0._0.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class modeloContainer : DbContext
    {
        public modeloContainer()
            : base("name=modeloContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<Instructor> Instructores { get; set; }
        public virtual DbSet<Estudiante> Estudiantes { get; set; }
        public virtual DbSet<Curso> Cursos { get; set; }
        public virtual DbSet<DetCrs_Est> DetCrs_Est { get; set; }
        public virtual DbSet<Leccion> Lecciones { get; set; }
        public virtual DbSet<Evaluacion> Evaluaciones { get; set; }
        public virtual DbSet<ResultadoEva> ResultadosEva { get; set; }
    }
}
